# Generated by Django 4.2.15 on 2024-10-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modblog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
